stages:
  split:
    cmd: python src/data/split_data.py --raw-path data/raw_data/raw.csv --output-dir data/processed_data
    deps:
      - src/data/split_data.py
      - data/raw_data/raw.csv
    outs:
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
      - data/processed_data/y_train.csv
      - data/processed_data/y_test.csv

  normalize:
    cmd: python src/data/normalize_data.py --processed-dir data/processed_data --scaler-path models/scaler.joblib
    deps:
      - src/data/normalize_data.py
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
    outs:
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/X_test_scaled.csv
      - models/scaler.joblib

  grid_search:
    cmd: python src/models/grid_search.py --processed-dir data/processed_data --output-path models/best_params.pkl
    deps:
      - src/models/grid_search.py
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
    outs:
      - models/best_params.pkl

  train:
    cmd: python src/models/train_model.py --processed-dir data/processed_data --params-path models/best_params.pkl --model-path models/model.joblib
    deps:
      - src/models/train_model.py
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
      - models/best_params.pkl
    outs:
      - models/model.joblib

  evaluate:
    cmd: python src/models/evaluate_model.py --processed-dir data/processed_data --model-path models/model.joblib --predictions-path data/processed_data/predictions.csv --metrics-path metrics/scores.json
    deps:
      - src/models/evaluate_model.py
      - data/processed_data/X_test_scaled.csv
      - data/processed_data/y_test.csv
      - models/model.joblib
    outs:
      - data/processed_data/predictions.csv
    metrics:
      - metrics/scores.json
